-- Create Database
CREATE DATABASE COLLEGE_DB;

USE DATABASE COLLEGE_DB;

-- Create Schema
CREATE SCHEMA COLLEGE_SCHEMA;

USE SCHEMA COLLEGE_SCHEMA;

SELECT CURRENT_DATABASE() AS DATABASE_NAME, 
       CURRENT_SCHEMA() AS SCHEMA_NAME;

-- Create Warehouse
CREATE WAREHOUSE COLLEGE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE COLLEGE_WH;

SELECT CURRENT_WAREHOUSE();

-- Create Table
CREATE TABLE STUDENTS (
    STUDENT_ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    YEAR INT,
    MARKS FLOAT
);

DESC TABLE STUDENTS;

-- Create Stage
CREATE STAGE STUDENT_STAGE;

SHOW STAGES;

-- Insert sample records
INSERT INTO STUDENTS VALUES
    (101, 'Arun', 'CSE', 3, 85),
    (102, 'Priya', 'BDA', 3, 91),
    (103, 'Rahul', 'ECE', 2, 78),
    (104, 'Meena', 'CSE', 3, 88),
    (105, 'Karthik', 'BDA', 2, 82);

-- SELECT
SELECT * FROM STUDENTS;

-- UPDATE
UPDATE STUDENTS
    SET MARKS = 90
    WHERE STUDENT_ID = 101;

SELECT * FROM STUDENTS
    WHERE STUDENT_ID = 101;

-- DELETE
DELETE FROM STUDENTS
    WHERE STUDENT_ID = 103;

-- Final SELECT to verify
SELECT * FROM STUDENTS;