-- Create table
CREATE TABLE TIME_TRAVEL_STUDENTS (
    STUDENT_ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    MARKS INT
);

-- Insert sample records
INSERT INTO TIME_TRAVEL_STUDENTS VALUES
    (301, 'Asha', 'CSE', 85),
    (302, 'Bala', 'BDA', 90),
    (303, 'Charan', 'ECE', 78),
    (304, 'Deepa', 'CSE', 92);

SELECT * FROM TIME_TRAVEL_STUDENTS
    ORDER BY STUDENT_ID;

-- Capture timestamp before making changes
SET BEFORE_CHANGE = CURRENT_TIMESTAMP();

SELECT $BEFORE_CHANGE;

-- UPDATE operation
UPDATE TIME_TRAVEL_STUDENTS
    SET MARKS = 99
    WHERE STUDENT_ID = 301;

SELECT * FROM TIME_TRAVEL_STUDENTS
    ORDER BY STUDENT_ID;

-- DELETE operation
DELETE FROM TIME_TRAVEL_STUDENTS
    WHERE STUDENT_ID = 303;

SELECT * FROM TIME_TRAVEL_STUDENTS
    ORDER BY STUDENT_ID;

-- Query table as it existed BEFORE the UPDATE/DELETE using Time Travel
SELECT *
    FROM TIME_TRAVEL_STUDENTS
    AT(TIMESTAMP => $BEFORE_CHANGE)
    ORDER BY STUDENT_ID;